import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="flex h-16 w-full items-center justify-between bg-background px-4 md:px-6">
      <Link href="#" className="flex items-center gap-2" prefetch={false}>
        <BookIcon className="h-6 w-6" />
        <span className="text-lg font-semibold">Mood Scribe</span>
      </Link>
      <nav className="flex items-center gap-4">
        <Link href="#" className="text-sm font-medium hover:underline hover:underline-offset-4" prefetch={false}>
          Journals
        </Link>
        <Link href="#" className="text-sm font-medium hover:underline hover:underline-offset-4" prefetch={false}>
          Write
        </Link>
        <Link href="#" className="text-sm font-medium hover:underline hover:underline-offset-4" prefetch={false}>
          Home
        </Link>
      </nav>
    </header>
        </body>
    </html>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}